### ISSUE TITLE
Compatibility with WooCommerce Chained Products

### ISSUE THREAD

**Issue by Mikcx** [isikom/woocommerce-sample#4]
It would be great if along with the compatibility that you have added for Min/Max plugin and Measurement Price Calculator plugin - you could add compatibility for [WooCommerce Chained Products plugin](https://www.woothemes.com/products/chained-products/).

Currently the issue is that if the main product has a chained product, it will also add the chained product to the sample when adding to the cart. Chained products should not be added to samples.

Thanks

**Comment by zauker** [comment]
I need the Chained Products Plugin to evaluate the integration.
If you have a license could you send me the plugin otherwise may I ask directly to woocommerce, for the others woocommerce plugins they provided a developer licence.

**Comment by zauker** [comment]
released with commit 6d23044ecf6d68735512bf75f6f48028b8c11fae
